apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inception-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: inception-server
    spec:
      containers:
      - name: inception-container
        image: ylashin/tensorflow-serving
        command:
        - /bin/sh
        - -c
        args:
        - tensorflow_model_server --port=7000 --model_name=dogs-vs-cats --model_base_path=/export/dogs-vs-cats
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: inception-service
  name: inception-service
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    app: inception-server
  type: LoadBalancer