apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: recommender-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommender-server
    spec:
      containers:
      - name: recommender-container
        image: ylashin/tensorflow-serving
        command:
        - /bin/sh
        - -c
        args:
        - tensorflow_model_server --port=8000 --model_name=Recommender --model_base_path=/Recommender
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: recommender-service
  name: recommender-service
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: recommender-server
  type: LoadBalancer